CREATE TABLE BRAND (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   brand VARCHAR(30)
);

CREATE TABLE MODELTYPE (
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   model_type VARCHAR(30),
   BRAND_ID INT NOT NULL,
   FOREIGN KEY (BRAND_ID) REFERENCES BRAND(id)
);

CREATE TABLE MODEL (
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   model VARCHAR(30),
   MODELTYPE_ID INT NOT NULL,
   FOREIGN KEY (MODELTYPE_ID) REFERENCES MODELTYPE(id)
);
