-- brand
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('1', 'Ace');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('2', 'Aceawtasd');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('3', 'Acer');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('4', 'Admiral');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('5', 'Advent');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('6', 'Adyson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('7', 'AGA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('8', 'Aiwa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('9', 'Akai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('10', 'Akari');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('11', 'Akurra');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('12', 'Alba');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('13', 'Allorgan');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('14', 'Amplivision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('15', 'Amstrad');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('16', 'Andrea Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('17', 'Anitech');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('18', 'AOC TV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('19', 'Apex Digital');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('20', 'Arcam');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('21', 'Arena');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('22', 'Argosy');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('23', 'Arise India');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('24', 'ASA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('25', 'Astor');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('26', 'Asuka');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('27', 'Atlantic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('28', 'Atwater Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('29', 'Audar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('30', 'Audiosonic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('31', 'Audiovox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('32', 'Automatic Radio Manufacturing');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('33', 'AVol');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('34', 'AWA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('35', 'Bace Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('36', 'Baird');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('37', 'Bang & Olufsen');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('38', 'Base');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('39', 'Basic Line');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('40', 'Baumann Meyer');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('41', 'Baur');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('42', 'Baycrest');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('43', 'Beko');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('44', 'Bell Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('45', 'BelTek Tv');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('46', 'BenQ');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('47', 'Bharat');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('48', 'Binatone');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('49', 'BiSA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('50', 'Blaupunkt');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('51', 'BLUE Edge');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('52', 'Blue Sky');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('53', 'Blue Star');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('54', 'Bondstec');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('55', 'BPL');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('56', 'Brandt');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('57', 'Brionvega');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('58', 'Britannia');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('59', 'BrokSonic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('60', 'BSR');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('61', 'BTC');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('62', 'Bush Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('63', 'Calbest Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('64', 'Candle');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('65', 'Capehart Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('66', 'Carrefour');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('67', 'Cascade');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('68', 'Cathay');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('69', 'Cello');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('70', 'Centurion');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('71', 'Certified Radio Labs');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('72', 'CGE');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('73', 'Changhong');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('74', 'ChiMei');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('75', 'Cimline');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('76', 'Citizen');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('77', 'Clairetone Electric Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('78', 'Clarivox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('79', 'Clatronic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('80', 'Coby');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('81', 'Colonial Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('82', 'Color Electronics Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('83', 'Conar Instruments');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('84', 'Condor');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('85', 'Conrac');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('87', 'Contec');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('88', 'Continental Edison');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('89', 'Cortron Industries');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('90', 'Cossor');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('91', 'Crown');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('92', 'Crystal');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('93', 'CS Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('94', 'CTC');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('95', 'Curtis Mathes Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('96', 'Cybertron');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('97', 'Daewoo');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('98', 'Dainichi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('99', 'Dansai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('100', 'Dayton');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('101', 'De Graaf');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('102', 'Decca');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('103', 'Deccacolour');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('104', 'Defiant');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('105', 'Dell');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('106', 'Delmonico International Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('107', 'Diamond vision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('108', 'Diboss');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('109', 'Dixi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('110', 'Dual');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('111', 'Dual Tec');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('112', 'Dumont');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('113', 'DuMont Laboratories');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('114', 'Durabrand');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('115', 'Dyanora');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('116', 'Dynatron');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('117', 'Edler');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('118', 'EKCO');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('119', 'Eki Electronics Corp');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('120', 'Elbe');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('121', 'Electrohome');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('122', 'Element Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('123', 'Elin');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('124', 'Elite');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('125', 'Elta');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('126', 'Emerson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('127', 'Emerson Radio and Phonograph');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('128', 'EMI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('129', 'English Electric Valve Company');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('130', 'Erres');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('131', 'Expert');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('132', 'Farnsworth Television and Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('133', 'Ferguson Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('134', 'Ferranti');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('135', 'Fidelity Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('136', 'Finlandia');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('137', 'Finlux');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('138', 'FIRST');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('139', 'Firstline');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('140', 'Fisher Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('141', 'Flint');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('142', 'Formenti');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('143', 'Frontech');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('144', 'Fujitsu');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('145', 'Funai Electric');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('146', 'Geloso');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('147', 'Geloso');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('148', 'Genes TV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('149', 'General Electric');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('150', 'General Electric Company plc');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('151', 'General Gold');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('152', 'Genexxa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('153', 'GoldStar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('154', 'Goodmans Industries');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('155', 'Gorenje');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('156', 'GPM');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('157', 'Gradiente');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('158', 'Graetz');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('159', 'Granada');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('160', 'Grandin');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('161', 'Grundig');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('162', 'Haier');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('163', 'Hannspree');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('164', 'Hanseatic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('165', 'Hantarex');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('166', 'Harvard International');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('167', 'Harvey Industries');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('168', 'HCM');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('169', 'Healing');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('170', 'Heath Company/Heathkit');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('171', 'Helkama');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('172', 'Helvar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('173', 'Hinari Domestic Applicanes');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('174', 'Hisawa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('175', 'Hisense[disambiguation needed]');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('176', 'Hitachi Ltd.');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('177', 'HMV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('178', 'Hoffman Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('179', 'Howard Radio ');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('180', 'Huanyu');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('181', 'Hypson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('182', 'Ice');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('183', 'Ices');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('184', 'Imperial');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('185', 'Indiana');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('186', 'Ingelen');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('187', 'Inno Hit');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('188', 'Insignia');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('189', 'Interfunk');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('190', 'Intervision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('191', 'Isukai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('192', 'ITS');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('193', 'ITT Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('194', 'ITT-KB');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('195', 'ITT-SEL');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('196', 'IZUMI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('197', 'Jensen Loudspeakers');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('198', 'JMB');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('199', 'JVC');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('200', 'Kaisui');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('201', 'Kamacrown');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('202', 'Kane Electronics Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('203', 'Kapsch');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('204', 'Kathrein');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('205', 'Kendo');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('206', 'Kent Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('207', 'Kingsley');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('208', 'Kloss Video');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('209', 'Kneissel');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('210', 'Kogan');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('211', 'Kolster-Brandes');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('212', 'Konka');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('213', 'Korpel');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('214', 'Koyoda');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('215', 'Lanix');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('216', 'LeEco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('217', 'Leyco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('218', 'LG Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('219', 'Liesenkötter');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('220', 'LLoyds');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('221', 'Loewe AG');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('222', 'Luma');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('223', 'Luxor');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('224', 'M Electronic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('225', 'Magnadyne');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('226', 'Magnafon');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('227', 'Magnasonic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('228', 'Magnavox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('229', 'Magnavox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('230', 'Maneth');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('231', 'Marantz');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('232', 'Marconiphone');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('233', 'Mark');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('234', 'Matsui');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('235', 'Mattison Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('236', 'McMichael Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('237', 'Mediator');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('238', 'Memorex');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('239', 'Mercury-Pacific');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('240', 'Metz');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('241', 'Micromax');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('242', 'Minerva');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('243', 'Minoka');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('244', 'Mirc Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('245', 'Mitsubishi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('246', 'Mivar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('247', 'Motorola');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('248', 'MT Logic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('249', 'MTC');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('250', 'Multitech');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('251', 'Muntz');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('252', 'Murphy Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('253', 'NEC');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('254', 'Neckermann');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('255', 'NEI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('256', 'Nelco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('257', 'NetTV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('258', 'Nikkai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('259', 'Nobliko');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('260', 'Nokia');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('261', 'Nordmende');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('262', 'North American Audio Inc.');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('263', 'Oceanic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('264', 'Olympic Radio and Television');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('265', 'Onida');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('266', 'Onwa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('268', '');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('269', 'Osaki');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('270', 'Oso');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('271', 'Osume');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('272', 'Otake');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('273', 'Otto Versand');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('274', 'Packard Bell Teledyne Packard Bell');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('275', 'Palladium');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('276', 'Panama');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('277', 'Panasonic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('278', 'Pathe Cinema');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('279', 'Pathe Marconi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('280', 'Pausa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('281', 'Perdio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('282', 'Peto Scott');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('283', 'Philco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('284', 'Philips');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('285', 'Philmore Manufacturing');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('286', 'Phonola');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('287', 'Pilot Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('288', 'Pilot Radio Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('289', 'Pioneer Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('290', 'Planar Systems');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('291', 'Polaroid');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('292', 'Prima');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('293', 'Profex');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('294', 'ProLine');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('295', 'ProScan');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('296', 'ProTech');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('297', 'Pulser');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('298', 'Pye');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('299', 'PyxScape');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('300', 'Quasar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('301', 'Quelle');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('302', 'Questa');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('303', 'R-Line');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('304', 'Radiola');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('305', 'Radiola');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('306', 'RadioMarelli');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('307', 'RadioShack');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('308', 'Rank Arena');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('309', 'Rauland Borg');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('310', 'Ravenswood');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('311', 'RBM');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('312', 'RCA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('313', 'Realistic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('314', 'Rediffusion');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('315', 'Regentone');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('316', 'REI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('317', 'Revox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('318', 'Rex');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('319', 'RFT');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('320', 'RGD');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('321', 'Roadstar');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('322', 'Rolls');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('323', 'SABA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('324', 'Saccs');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('325', 'Saisho');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('326', 'Salora');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('327', 'Salora International');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('328', 'Sambers');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('329', 'Sampo Corp. of America');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('330', 'Samsung');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('331', 'Sanabria Television Corporation');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('332', 'Sandra');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('333', 'Sansui');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('334', 'Sanyo');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('335', 'SBR');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('336', 'Sceptre Incorporated');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('337', 'Schaub Lorenz');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('338', 'Schneider');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('339', 'Schneider');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('340', 'Schneider Electric');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('341', 'Sears');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('342', 'SEG');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('343', 'SEI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('344', 'Sei-Sinudyne');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('345', 'Seiki Digital');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('346', 'Selco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('347', 'Sentra');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('348', 'Setchell Carlson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('349', 'Seura[2]');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('350', 'Sharp');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('351', 'Shorai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('352', 'Siarem');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('353', 'Siemens AG');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('354', 'Silo Digital');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('355', 'Silver');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('356', 'Silvertone');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('357', 'Sinudyne');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('358', 'Skyworth[disambiguation needed]');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('359', 'Sobell');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('360', 'Solavox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('361', 'Soniq');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('362', 'Sonitron');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('363', 'Sonoko');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('364', 'Sonolor');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('365', 'Sonora');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('366', 'Sontec');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('367', 'Sony');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('368', 'Soundwave');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('369', 'Soyo');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('370', 'Sparc');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('371', 'Stern');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('372', 'Stewart-Warner');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('373', 'Stromberg Carlson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('374', 'Sunkai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('375', 'SunLite TV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('376', 'Supra');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('377', 'Susumu');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('378', 'Sylvania');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('379', 'Symphonic Electronic Corp');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('380', 'Symphonic Radio and Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('381', 'Sysline');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('382', 'Sèleco');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('383', 'Tandy');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('384', 'Tatung Company');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('385', 'TCL[disambiguation needed]');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('386', 'Tec');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('387', 'Tech-Master');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('388', 'Technema');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('389', 'Technics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('390', 'Technika');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('391', 'Technika TV');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('392', 'Technisat');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('393', 'Tecnimagen');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('394', 'TECO');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('395', 'Teleavia');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('396', 'Telefunken');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('397', 'Telemeister');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('398', 'Telequip');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('399', 'Teletech');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('400', 'Teleton');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('401', 'Teletronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('402', 'Television Inc.');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('403', 'Tensai');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('404', 'Texet');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('405', 'Thomson SA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('406', 'Thorn Electrical Industries');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('407', 'Thorn EMI');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('408', 'TMA');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('409', 'Tomashi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('410', 'Toshiba');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('411', 'TP Vision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('412', 'TPV Technology');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('413', 'Transvision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('414', 'Trav-Ler Radop');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('415', 'Travelers Electronics Co.');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('416', 'Trinium Electronics Philippines');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('417', 'Triumph');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('418', 'Uher');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('419', 'Ultra');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('420', 'Ultravox');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('421', 'United States Television Manufacturing Corp.');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('422', 'Universum');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('423', 'V WORLD');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('424', 'Veon');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('425', 'Vestel');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('426', 'Videocon');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('427', 'Videosat');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('428', 'Videotechnic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('429', 'Videoton');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('430', 'Viewsonic');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('431', 'Vision');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('432', 'Vistron');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('433', 'Vizio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('434', 'Vu');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('435', 'Warwick');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('436', 'Watson');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('437', 'Watt Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('438', 'Wells-Gardner');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('439', 'Westinghouse');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('440', 'Westinghouse Digital');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('441', 'Weston Electronics');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('442', 'White-Westinghouse');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('443', 'X2GEN');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('444', 'Yoko');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('445', 'Yoko');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('446', 'Zanussi');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('447', 'Zenith Radio');
INSERT INTO `ircodes`.`BRAND` (`id`, `brand`) VALUES ('448', 'Zonda');

-- typeMODELTYPE