-- Les villes et les quartiers du GTA
CREATE TABLE VILLES (
   VILLES_ID INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR (30),
   PRIMARY KEY (VILLE_ID)
   );

CREATE TABLE QUARTIERS (
   QUARTIERS_ID INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR(30)
   PRIMARY KEY (QUARTIERS_ID)
   );

CREATE TABLE ENDROITS (
   VILLES_ID INT NOT NULL,
   QUARTIERS_ID INT NOT NULL
   );