DROP TABLE BRAND;

CREATE TABLE BRAND (
   BRAND_ID INT NOT NULL PRIMARY KEY,
   BRAND_NAME VARCHAR(30)
   );

-- modele
-- DROP TABLE MODEL;

CREATE TABLE MODEL (
   BRAND_ID INT NOT NULL,
   MODEL_ID INT NOT NULL PRIMARY KEY,
   MODEL_NAME VARCHAR(30),
   FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);
