version: '2'
services:
   web:
      build: site
      ports:
       - "7000:5000"
      depends_on:
       - influxdb
   
   influxdb:
      image: tutum/influxdb
      ports:
       - "8083:8083"
       - "8086:8086"
      expose:
       - "8090"
       - "8099"
      environment:
       - PRE_CREATE_DB="wadus"

   grafana:
      image: grafana/grafana
      ports:
       - "3000:3000"
      depends_on:
       - influxdb

