-- information sur les divers types d'aliments
CREATE TABLE TYPE_ALIMENTS (
   TYPE_ALIMENT_ID INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR (30), 
   PRIMARY KEY (TYPE_ALIMENT_ID)
   );

CREATE TABLE ALIMENTS (
   ALIMENT_ID INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR(30),
   TYPE_ALIMENT_ID INT, 
   FOREIGN KEY (TYPE_ALIMENT_ID) REFERENCES TYPE_ALIMENTS(TYPE_ALIMENT_ID),
   PRIMARY KEY (ALIMENT_ID)
   );

CREATE TABLE VALEUR_NUTRITIF (
   VALEUR_NUTRITIF_ID INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR(30),
   PRIMARY KEY (ALIMENT)
   );

